<?php
namespace spax\impl;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-19 at 12:18:46.
 */
class ArrayAttributesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ArrayAttributes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayAttributes;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers spax\impl\ArrayAttributes::addAttribute
     * @todo   Implement testAddAttribute().
     */
    public function testAddAttribute()
    {
        $this->object->addAttribute('ns1:element1', 'element1', 'namespace1/1.0', 'CDATA');
        $index = $this->object->getIndex('ns1:element1');
        $this->assertEquals($index, 0);
    }

    /**
     * @covers spax\impl\ArrayAttributes::getLength
     * @todo   Implement testGetLength().
     */
    public function testGetLength()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getLocalName
     * @todo   Implement testGetLocalName().
     */
    public function testGetLocalName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getQName
     * @todo   Implement testGetQName().
     */
    public function testGetQName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getTypeByNamespace
     * @todo   Implement testGetTypeByNamespace().
     */
    public function testGetTypeByNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getUri
     * @todo   Implement testGetUri().
     */
    public function testGetUri()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getValueByNamespace
     * @todo   Implement testGetValueByNamespace().
     */
    public function testGetValueByNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getIndex
     * @todo   Implement testGetIndex().
     */
    public function testGetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers spax\impl\ArrayAttributes::getIndexByNamespace
     * @todo   Implement testGetIndexByNamespace().
     */
    public function testGetIndexByNamespace()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
